name: Generate PDF Documentation

on:
  push:
    branches:
      - main
      - fix_index
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    # Note: this container does not have bash! Using sh instead.
    container: pandoc/latex:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build Manual PDF
      run: ./docs/soar_manual/build.sh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: soar-manual-pdf
        path: output/
        if-no-files-found: error
