name: Generate PDF Documenatation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    container: pandoc/latex:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Debug environment
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Files in docs directory:"
        ls -la ./docs
        echo "Files in docs/soar_manual directory:"
        ls -la ./docs/soar_manual
    - name: Build Manual PDF
      run: ./docs/soar_manual/build.sh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PDFs
        path: output
